site_name: Jacob Prometheus Book
site_description: "Jacob's Prometheus 技术实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '监控解决方案': 
    - '1 监控解决方案：10个 Kubernetes 监控工具': 'chap0/1monitor_tools10.md'
    - '2023 云原生系统监控': 'chap1/11Prom_intro_2023-CN.md'
  - 'Prometheus技术介绍,K8S Metrics介绍&查看':
    - '第零节 Promethues 应用监控的一些实践': 'chap1/57prometheus_best_practice.md'
    - '第一节 Prometheus 系统介绍 2022' : 'chap1/1prometheus2022.md'
    - '第二节 深入Prometheus设计-指标定义与分类(PromQL)': 'chap1/18Adv_Prometheus_index_classfication.md'
    - '第三节 kube-state-metrics': 'chap1/k8s_adv39_kube_state_metrics.md'
    - '第四节 Metrics Server 安装': 'chap1/17Adv_K8S_Metrics_Server.md'
    - '第五节 Install Kubernetes Metrics Server on SAP Converged Cloud': 'chap1/20Install_metrics_server_SAP_CC.md'
    - '第六节 Kubernetes HPA 使用详解(Metrics Server/CPU/Mem/adapater)': 'chap1/38k8s_hpa_metricsserver.md'
    - '第七节 为Go应用添加Prometheus监控指标': 'chap1/55prometheus_go_metrics.md'
    - '第八节 从kubectl top看K8S监控原理': 'chap1/37kubectl_top.md'
    - '第九节 通过 kube-state-metrics 添加 CRD 状态指标': 'chap1/9kube-state-metrics_crd.md'
    - '第十节 kube-state-metrics 在大规模集群下的优化(2023)': 'chap1/10kube-state-metrics-cluster-opt.md'
  - 'Prometheus on Linux':
    - '第一节 Centos7 Prometheus安装部署+监控+绘图+告警': 'chap2/19centos7_Prometheus_Alertmanager_Grafana.md'
    - '第二节 使用Node Exporter监控Linux主机&常用监控指标': 'chap2/59node_exporter.md'
    - '第三节 基于Prometheus构建MySQL可视化监控平台': 'chap2/36Prometheus_Mysql.md'
    - '第四节 官方 mysqld_exporter支持抓取多MySQL实例': 'chap2/4mysql_exporter.md'
    - '第五节 使用 Grafana、Prometheus 和 Slack 构建一个简单的 ChatOps 机器人': 'chap2/5prom_grafana_chatops.md'
  - '手动部署Kubernetes Prometheus':
    - '第一节 Kubernetes使用Prometheus搭建监控平台(2018)': 'chap3/1prometheus_setup.md'
    - '第二节 Prometheus报警 && AlertManager实战（2018）': 'chap3/2prometheus_AlertManager.md'
    - '第三节 Grafana 显示参数设置(2018)': 'chap3/3changes_on_Grafana.md'
    - '第四节 在 Kubernetes 中手动部署 Prometheus (adv)': 'chap3/4Adv_Prometheus_setup.md'
    - '第五节 应用监控（Metrics/Exporter的配置）': 'chap3/5Adv_Prometheus_monitor.md'
    - '第六节 监控K8S集群节点&Node-exporter DaemonSet': 'chap3/6Adv_K8S_Nodes_monitor.md'
    - '第七节 监控常用资源对象（容器/apiserver/Service监控/kube-state-metric）': 'chap3/7Adv_K8S_Resource_monitor.md'
    - '第八节 Grafana 在 Kubernetes 中的使用': 'chap3/8Adv_K8S_Grafana.md'
    - '第九节 报警神器 AlertManager 的使用': 'chap3/10Adv_k8s_AlertManger.md'
    - '第十节 Prometheus 删除数据指标': 'chap3/16Adv_Prometheus_Del_index.md'
    - '第十一节 Prometheus中使用PrometheusAlert进行聚合报警': 'chap3/50PrometheusAlert.md'
    - '第十二节 监控Kubernetes集群的GPU资源': 'chap3/12gpu_monitor.md'
    - '第十三节 AlertManager何时报警': 'chap3/29AlertManager_SendAlerts_when.md'
    - '第十四节 Prometheus监控外部Kubernetes集群': 'chap3/41Prometheus_Monitor_OutCluster.md'
  - '玩转Prometheus Operator':
    - '第一节 Prometheus Operator 初体验': 'chap4/11Adv_Prometheus_Operator.md'
    - '第二节 使用 Prometheus Operator 监控 etcd': 'chap4/13Adv_Prometheus_Operator_etcd.md'
    - '第三节 Prometheus Operator 自定义报警': 'chap4/14Adv_Prometheus_Operator_alarm.md'
    - '第四节 Add Custom Alert and Send Alert Email with Alertmanager': 'chap4/22Customize_Alert_Email.md'
    - '第五节 Prometheus 黑盒监控': 'chap4/24Kubernetes_Prometheus_blackbox.md'
    - '第六节 Troubleshooting ServiceMonitor changes': 'chap4/32Prometheus_troubleshoot_Servicemonitor.md'
    - '第七节 使用ssl_exporter监控K8S集群证书': 'chap4/43Prometheus_operator_ssl_exporter.md'
    - '第八节 Operator2021-使用KubeNurse进行集群网络监控': 'chap4/44Prometheus_KubeNurse.md'
    - '第九节 Prometheus Operator安装配置(2021)': 'chap4/45Prom-operator_2021.md'
    - '第十节 Traefik之使用Prometheus Operator进行监控报警2021': 'chap4/46Prometheus_traefik.md'
    - '第十一节 Operator使用AlertmanagerConfig进行报警配置': 'chap4/47Prometheus_opt_AlertmanagerConfig.md'
    - '第十二节 通过Prometheus来做SLI/SLO监控展示': 'chap4/49Prometheus_SLI_SLO.md'
    - '第十三节 Prometheus使用missing-container-metrics监控Pod oomkill': 'chap4/51missing-container-metrics.md'
    - '第十四节 如何在Prometheus中进行黑盒监控(ICMP/DNS/TCP/HTTP/gRPC)': 'chap4/chap4_blackbox.md'
    - '第十五节 Prometheus Operator中探针的使用（Blackbox Exporter）': 'chap4/chap4_Operator_probe.md'
  - 'Prometheus服务发现':
    - '第一节 Prometheus服务的自动发现使用': 'chap5/53Prometheus_auto_discovery.md'
    - '第二节 Prometheus Relabeling重新标记的使用': 'chap5/52Prometheus_Relabeling.md'
    - '第三节 如何使用Prometheus仪表化应用': 'chap5/54prometheus_go_metrics_guideline.md'
  - 'Jam prometheus Monitor':
    - 'Chap1 Alertmanager alerts with Amazon SES SMTP': 'chap6/25Alertmanager_AWS_SES.md'
    - 'Chap2 Prometheus Operator Monitor on ArgoCD': 'chap6/26Prometheus_Monitor_Argocd.md'
    - 'Chap3 Prometheus Operator Monitor on ElasticSearch': 'chap6/27Prometheus_Monitor_elasticsearch.md'
    - 'Chap4 Prometheus Operator Monitor on Rabbitmq': 'chap6/31Prometheus_Monitor_rabbitmq.md'
    - 'Chap5 Prometheus Operator Monitor on Memcached': 'chap6/33Prometheus_Monitor_memcached.md'
  - 'Prometheus-Adapter':
    - '应用进行自定义指标扩缩容 by Prometheus-Adapter and Flask-Exporter': 'chap7/23Kubernetes_Scale_Prometheus-Adapter.md'
  - 'PromQL学习':
    - '1 初识 PromQL': 'chap8/1Promql_basic1.md'
    - '2 PromQL 操作符 & 内置函数': 'chap8/2Promql_basic2.md'
    - '3 PromQL 内置函数': 'chap8/3Promql_basic3.md'
    - '4 PromQL简单示例': 'chap8/4Promql_basic4.md'
    - '5 在 HTTP API中使用 PromQL': 'chap8/5Promql_basic5.md'
    - '6 Prometheus记录规则的使用(Recording Rule)': 'chap8/6Promql_adv1.md'
    - '7 PromQL查询之rate函数的使用': 'chap8/56prometheus_promql_rate.md'
    - '8 解决Prometheus监控Kubernetes Job误报的坑': 'chap8/60prometheus_job.md'
    - '9 使用 Prometheus PromQL时需要避免这6个错误': 'chap8/9promql_6errors.md'
  - 'Awesome alerts rules':
    - '1 Basic resource monitoring': 'chap9/1basic_resource.md'
    - '2 Databases and brokers': 'chap9/2database_broker.md'
    - '3 Reverse proxies and load balancers': 'chap9/3proxy_lb.md'
    - '4 Runtimes': 'chap9/4runtimes.md'
    - '5 Orchestrators': 'chap9/5Orchestrators.md'
    - '6 Network, security and storage': 'chap9/6network_sec_storage.md'
    - '7 Others': 'chap9/7other.md'
    - '8 Alert Sleep Peacefully': 'chap9/8Alerting_sleep.md'
  - '数据可视化&Grafana Plugin':
    - '1 使用 Grafana 构建你的第一个仪表盘': 'chap10/58grafana_init.md'
    - '2 优秀的Grafana K8S 插件-DevOpsProdigy KubeGraf': 'chap10/28Grafana_plugin_DevOpsProdigy.md'
    - '3 用 Kubernetes darks资源对象创建Grafana Dashboard': 'chap10/30Create_Grafana_dashboards.md'
    - '4 Grafana 图表加速神器-Trickster': 'chap10/48grafana_Trickster.md'
    - '5 使用读写分离模式扩展 Grafana Loki': 'chap10/5Grafana_Loki.md'
  - 'Prometheus(OpenTelemetry)架构设计与工具平台':
    - '1 DeepFlow AutoTagging之Prometheus标签标准化': 'chap13/1deepflow.md'
    - '2 Prometheus与OpenTelemetry该选哪个？': 'chap13/2Prometheus_opentele.md'
    - '3 Prometheus的四种指标类型': 'chap13/3Prometheus_index.md'
    - '4 透彻理解OpenTelemetry': 'chap13/4OpenTelemetry.md'
    - '5 使用OpenTelemetry Tracing最大化Kubernetes效率': 'chap13/4OpenTelemetry_tracing.md'
  - 'Thanos':
    - '第一节 大规模场景下Prometheus的优化手段&Thanos架构详解': 'chap11/39Thanos_tutorial.md'
    - '第二节 使用Thanos实现Prometheus的高可用介绍': 'chap11/34Thanos_intro.md'
    - '第三节 Prometheus高可用Thanos学习-sidercar和query&Thanos部署': 'chap11/35Thanos_install.md'
    - '第四节（2022）如何选择Thanos的Sidecar和Receiver两种模式？': 'chap11/61thanos_sidecar_receiver.md'
    - '第五节（2022）使用Thanos查询前端优化查询性能': 'chap11/62thanos_query.md'
    - '第六节 (Thaos1-2022)大规模场景下Prometheus的优化手段': 'chap11/63prometheus_optimiztion.md'
    - '第七节 (Thaos2-2022)Thanos架构详解': 'chap11/64thanos_detail.md'
    - '第八节 (Thaos3-2022)Thanos部署与实践': 'chap11/65thanos_setup.md'
    - '第九节（2022）Thanos Ruler组件的使用': 'chap11/66thanos_ruler.md'
  - 'VictoriaMetrics':
    - '第一节 Prometheus远程存储VictoriaMetrics简介': 'chap12/67vm_intro.md'
    - '第二节 Prometheus长期远程存储方案VictoriaMetrics入门实践': 'chap12/68vm_setup.md'
    - '第三节 VictorialMetrics 集群模式的使用': 'chap12/69vm_cluster.md'
    - '第四节 使用vmagent代替Prometheus采集监控指标': 'chap12/70vm_vmagent.md'
    - '第五节 使用Victoria Metrics Operator管理VM集群': 'chap12/71vm_operator.md'
    - '第六节 使用 vmalert 代替 Prometheus 监控报警': 'chap12/72vm_vmalert.md'
    - '第七节 对Prometheus兼容的时序数据库进行压力测试': 'chap12/73vm_pressure.md'
  - 'APM 工具及功能介绍':
    - '第一节 APM产品落地实战': 'chap_apm/1apm_prods.md'
    - '第二节 APM + OpenTracing原理': 'chap_apm/2opentracing.md'
    - '第三节 怎么理解分布式链路追踪技术？': 'chap_apm/3apm_tracing.md'
    - '第四节 在生产环境中如何选择靠谱的APM系统？': 'chap_apm/4apm_prod.md'
    - '第六节 聊聊可观测性之数据模型': 'chap_apm/6k8s_watching.md'
  - 'OpenTelemetry 介绍':
    - '0 OpenTelemetry保姆入门攻略可PPT-2023': 'chap_ot/0OpenTelemetrey_intro.md'
    - '1 云原生可观测 OpenTelemetry 基础知识': 'chap_ot/1OpenTelemetry_intro.md'
    - '2 使用 OpenTelemetry Collector 采集 Kubernetes 指标数据': 'chap_ot/1OpenTelemetry_k8s_metrics.md'
    - '3 使用 OpenTelemetry Collector 收集 Kubernetes 日志数据': 'chap_ot/5OpenTelemetry_log.md'
    - '4 Sentry+OpenTelemetry前后端全链路打通': 'chap_apm/5apm_Sentry.md'
    - '5 使用 OpenTelemetry Tracing 了解您的微服务': 'chap_apm/2OpenTelemetry_MS.md'
    - '6 使用 OpenTelemetry Tracing 最大化Kubernetes效率': 'chap_apm/3OpenTelemetry_K8S.md'
    - '7 聊聊可观测性之数据模型': 'chap_apm/4OpenTelemetry_datamon.md'
    - '8 Java 应用通过 OpenTelemetry API 实现手动埋点' : 'chap_apm/6OpenTelemetry_java.md'


repo_url: https://github.com/Chao-Xi/jxprombook.git
repo_name: "jxprombook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'