site_name: Jacob Prometheus Book
site_description: "Jacob's Prometheus 技术实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Prometheus技术介绍,K8S Metrics介绍&查看':
    - '第一节 Prometheus 系统介绍 2022' : 'chap1/1prometheus2022.md'
    - '第二节 深入Prometheus设计-指标定义与分类(PromQL)': 'chap1/18Adv_Prometheus_index_classfication.md'
    - '第三节 kube-state-metrics': 'chap1/k8s_adv39_kube_state_metrics.md'
    - '第四节 Metrics Server 安装': 'chap1/17Adv_K8S_Metrics_Server.md'
    - '第五节 Install Kubernetes Metrics Server on SAP Converged Cloud': 'chap1/20Install_metrics_server_SAP_CC.md'
    - '第六节 Kubernetes HPA 使用详解(Metrics Server/CPU/Mem/adapater)': 'chap1/38k8s_hpa_metricsserver.md'
    - '第七节 从kubectl top看K8S监控原理': 'chap1/37kubectl_top.md'
  - 'Prometheus on Linux':
    - '第一节 Centos7 Prometheus安装部署+监控+绘图+告警': 'chap2/19centos7_Prometheus_Alertmanager_Grafana.md'
    - '第二节 使用Node Exporter监控Linux主机&常用监控指标': 'chap2/59node_exporter.md'
    - '第三节 基于Prometheus构建MySQL可视化监控平台': 'chap2/36Prometheus_Mysql.md'
  - '手动部署Kubernetes Prometheus':
    - '第一节 Kubernetes使用Prometheus搭建监控平台(2018)': 'chap3/1prometheus_setup.md'
    - '第二节 Prometheus报警 && AlertManager实战（2018）': 'chap3/2prometheus_AlertManager.md'
    - '第三节 Grafana 显示参数设置(2018)': 'chap3/3changes_on_Grafana.md'
    - '第四节 在 Kubernetes 中手动部署 Prometheus (adv)': 'chap3/4Adv_Prometheus_setup.md'
    - '第五节 应用监控（Metrics/Exporter的配置）': 'chap3/5Adv_Prometheus_monitor.md'
    - '第六节 监控K8S集群节点&Node-exporter DaemonSet': 'chap3/6Adv_K8S_Nodes_monitor.md'
    - '第七节 监控常用资源对象（容器/apiserver/Service监控/kube-state-metric）': 'chap3/7Adv_K8S_Resource_monitor.md'
    - '第八节 Grafana 在 Kubernetes 中的使用': 'chap3/8Adv_K8S_Grafana.md'
    - '第九节 报警神器 AlertManager 的使用': 'chap3/10Adv_k8s_AlertManger.md'
    - '第十节 Prometheus 删除数据指标': 'chap3/16Adv_Prometheus_Del_index.md'
    - '第十一节 Prometheus中使用PrometheusAlert进行聚合报警': 'chap3/50PrometheusAlert.md'
    - '第十二节 监控Kubernetes集群的GPU资源': 'chap3/12gpu_monitor.md'
    - '第十三节 AlertManager何时报警': 'chap3/29AlertManager_SendAlerts_when.md'
    - '第十四节 Prometheus监控外部Kubernetes集群': 'chap3/41Prometheus_Monitor_OutCluster.md'
  - '玩转Prometheus Operator':
    - '第一节 Prometheus Operator 初体验': 'chap4/11Adv_Prometheus_Operator.md'
    - '第二节 使用 Prometheus Operator 监控 etcd': 'chap4/13Adv_Prometheus_Operator_etcd.md'
    - '第三节 Prometheus Operator 自定义报警': 'chap4/14Adv_Prometheus_Operator_alarm.md'
    - '第四节 Add Custom Alert and Send Alert Email with Alertmanager': 'chap4/22Customize_Alert_Email.md'
    - '第五节 Prometheus 黑盒监控': 'chap4/24Kubernetes_Prometheus_blackbox.md'
    - '第六节 Troubleshooting ServiceMonitor changes': 'chap4/32Prometheus_troubleshoot_Servicemonitor.md'
    - '第七节 使用ssl_exporter监控K8S集群证书': 'chap4/43Prometheus_operator_ssl_exporter.md'
    - '第八节 Operator2021-使用KubeNurse进行集群网络监控': 'chap4/44Prometheus_KubeNurse.md'
    - '第九节 Prometheus Operator安装配置(2021)': 'chap4/45Prom-operator_2021.md'
    - '第十节 Traefik之使用Prometheus Operator进行监控报警2021': 'chap4/46Prometheus_traefik.md'
    - '第十一节 Operator使用AlertmanagerConfig进行报警配置': 'chap4/47Prometheus_opt_AlertmanagerConfig.md'
    - '第十二节 通过Prometheus来做SLI/SLO监控展示': 'chap4/49Prometheus_SLI_SLO.md'
    - '第十三节 Prometheus 使用 missing-container-metrics 监控 Pod oomkill': 'chap4/51missing-container-metrics.md'
  - 'APM 工具及功能介绍':
    - '第一节 APM产品落地实战': 'chap_apm/1apm_prods.md'

repo_url: https://github.com/Chao-Xi/jxprombook.git
repo_name: "jxprombook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'