site_name: Jacob Prometheus Book
site_description: "Jacob's Prometheus 技术实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Prometheus技术介绍,K8S Metrics介绍&查看':
    - '第一节 Prometheus 系统介绍 2022' : 'chap1/1prometheus2022.md'
    - '第二节 深入Prometheus设计-指标定义与分类(PromQL)': 'chap1/18Adv_Prometheus_index_classfication.md'
    - '第三节 kube-state-metrics': 'chap1/k8s_adv39_kube_state_metrics.md'
    - '第四节 Metrics Server 安装': 'chap1/17Adv_K8S_Metrics_Server.md'
    - '第五节 Install Kubernetes Metrics Server on SAP Converged Cloud': 'chap1/20Install_metrics_server_SAP_CC.md'
    - '第六节 Kubernetes HPA 使用详解(Metrics Server/CPU/Mem/adapater)': 'chap1/38k8s_hpa_metricsserver.md'
    - '第七节 从kubectl top看K8S监控原理': 'chap1/37kubectl_top.md'
  - 'Prometheus on Linux':
    - '第一节 Centos7 Prometheus安装部署+监控+绘图+告警': 'chap1/19centos7_Prometheus_Alertmanager_Grafana.md'
    - '第二节 使用Node Exporter监控Linux主机&常用监控指标': 'chap1/59node_exporter.md'
    - '第三节 基于Prometheus构建MySQL可视化监控平台': 'chap1/36Prometheus_Mysql.md'

repo_url: https://github.com/Chao-Xi/jxprombook.git
repo_name: "jxprombook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'